-- Template: create partition for a CBETA series letter(s).
-- Generated by: python -m canon.ingest.ensure_partitions --corpus /home/zenlook/cbeta-text

-- Example manual:
-- CREATE TABLE IF NOT EXISTS canon_chunks_X PARTITION OF canon_chunks FOR VALUES IN ('X');
-- CREATE INDEX IF NOT EXISTS canon_chunks_X_canon_id_idx ON canon_chunks_X (canon_id);
-- CREATE INDEX IF NOT EXISTS canon_chunks_X_embedding_hnsw ON canon_chunks_X
--   USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
-- CREATE INDEX IF NOT EXISTS canon_chunks_X_tsv_gin ON canon_chunks_X USING gin (tsv);
